# 服务端口号
server:
  port: 8001
# 服务名称
spring:
  application:
    name: cloud-payment-service
    # 配置zipkin
    zipkin:
#      base-url: http://192.168.60.130:9411
      base-url: http://localhost:9411
    sleuth:
      sampler:
        # 设置采样率,采样率的值介于 0到1之间，1，则表示全部采集
      probability: 1

  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点可不配置，集群模式下必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版的配置，为了方便演示，就使用 7001 和 8001
       defaultZone: http://localhost:7001/eureka
      # 集群版本的配置
       # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  # 配置主机名和ip地址显示，这个是actuator监控时使用
  instance:
    instance-id: payment8001
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    # Eureka客户端想服务端发送心跳的时间间隔（单位为秒，默认是30秒）
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳之后等待时间上限，（单位为秒，默认是90秒中，超时的话就会将服务剔除）
    lease-expiration-duration-in-seconds: 2

# 配置mybatis
mybatis:
  # mapper文件路径
  mapper-locations: classpath:mapper/*.xml
  # 所有的Entity别名类所在的包
  type-aliases-package: com.bberzhou.springcloud.entities