server:
  port: 3344
spring:
  application:
    # 注册进Eureka服务器的名称
    name: cloud-config-center

  cloud:
    config:
      server:
        git:
          # github上面的仓库名称
          uri: https://github.com/bberzhou/springcloud-config.git
          # 搜索目录
          search-paths:
            - springcloud-config
      # 读取分支
      label: main
      #{label}/{application}-{profile}.yml ，可以配置main或者dev分支

      # 注意，如果使用 {application}-{profile}.yml，默认得label是master，
      # org.springframework.cloud.config.server.environment.NoSuchLabelException: No such label: master，
      # 现在GitHub默认是main就会报错

# 增加rabbitmq的相关配置
  rabbitmq:
    # 虚拟机的 ip地址
    host: 192.168.60.130
    # 注意端口：15672 是web管理界面的端口，5672是MQ访问的端口
    port: 5672
    username: admin
    password: yourpassword



# 将这个服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka



# 服务器添加rabbitmq 之后，需要进行相关的配置，暴露bus 刷新配置的端点
# 通过这样配置以后，就只需要刷新 服务端的 就可以同步刷新所有的客户端
# curl -X POST "http://localhost:3344/actuator/bus-refresh"
#
management:
  # 暴露bus 刷新配置的端点
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'