server:
  # 配置服务端口
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # nacos 服务注册中心的地址吗，单机版的nacos ，默认端口是8848，部署在Ubuntu服务器上的
        server-addr: 192.168.60.130:8848

    sentinel:
      transport:
        # 配置sentinel的 dashboard 地址，默认启动是8080，部署在Ubuntu服务器上的
        # 这个是前台展示的端口
        dashboard: 192.168.60.130:8080
        # 默认是 8719 端口，加入被占用会自动从8719开始一次 +1 扫描，直到找到没被占用的端口
        # 这个是sentinel后台与微服务通信的服务端口
        port: 8719
        # 配置sentinel的持久化操作
        datasource:
          ds1:
            nacos:
              server-addr: 192.168.60.130:8848
              dataId: ${spring.application.name}
              groupId: DEFAULT_GROUP
              data_type: json
              rule_type: flow

# 配置持久化时，需要在naocs里面添加 data id 为对应应用名 cloudalibaba-sentinel-service的相关配置
#  [
#    {
#      "resource":"/reateLimit/byUrl",  资源名称
#      "limitApp":"default", 来源应用
#      "grade":1,  阈值类型，0表示线程数，1表示QPS
#      "count":1    单机阈值
#        "strategy":0,    流控模式，0表示直接，1表示关联，2表示链路
#      "controlBehavior":0,   流控效果，0表示快速失败，1表示为warm up， 2表示排队等待
#      "clusterMode":false   是否是集群
#    }
#  ]

management:
  endpoints:
    web:
      exposure:
        include: "*"
# 开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true