server:
  port: 3366

spring:
  application:
    name: config-client
  cloud:
    # config 客户端配置
    config:
      # 分支名称，注意现在github已经使用main 取代了master
      label: main
      # 配置文件名称
      name: config
      # 读取后缀名称
      profile: dev
      # 上述这三个综合起来，main分支上config-dev.yml的配置文件被读取http://config-3344.com:3344/main/config-dev.yml

# 将服务注册到eureka地址
eureka:
  client:
    service-url: http://localhost:7001/eureka


# 对外暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
