# 8006 表示注册到consul 服务器的支付服务提供者端口号
server:
  port: 8006

# 服务别名------------注册consul到注册中心名称
spring:
  application:
    name: cloud-providerconsul-payment
  cloud:
    # consule注册中心地址
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
      # hostname: 127.0.0.1