server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        # 配置Nacos的地址
        server-addr: 192.168.60.130:8848


# 消费者将要去访问的微服务名称（在nacos成功注册的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider
